
---
- hosts: testing
  tasks:
   - name: Download Java
     command: sudo yum install java-1.8.0-openjdk -y

   - name: Unpack archive
     command: sudo yum install java-1.8.0-openjdk-devel -y

   - name: check java version
     command: java -version

   - name: Create Folder
     file:
      path: /home/ec2-user/tomcat
      state: directory
      mode: 0755
      owner: ec2-user
      group: ec2-user

   - name: Download Tomcat
     get_url: url=https://archive.apache.org/dist/tomcat/tomcat-8/v8.0.27/bin/apache-tomcat-8.0.27.tar.gz dest=/home/ec2-user/tomcat

   - name: Extract archive
     unarchive: src=/home/ec2-user/tomcat/apache-tomcat-8.0.27.tar.gz dest=/home/ec2-user/tomcat remote_src=yes
  
   - name: Download Application
     get_url: url=https://s3.amazonaws.com/vetinary-care-solutions/CloudAssessment.war dest=/home/ec2-user/
   - name: start apache-tomcat-8.0.27
     command: /home/ec2-user/tomcat/apache-tomcat-8.0.27/bin/startup.sh

   - name: copy petclinic.war
     shell: cp /home/ec2-user/CloudAssessment.war /home/ec2-user/tomcat/apache-tomcat-8.0.27/webapps/

   - name: stop apache-tomcat-8.0.27
     command: nohup "//home/ec2-user/tomcat/apache-tomcat-8.0.27/bin/shutdown.sh"
   
   - name: start apache-tomcat-8.0.27
     command: nohup "/home/ec2-user/tomcat/apache-tomcat-8.0.27/bin/startup.sh"

    
